### PR TITLE
Create event design

### PR DESCRIPTION
**Pull request by crigor**
Not yet done but I want to ask help with the code. How do you set the start_time if you use 2 dropdowns -- one for the hour and one for AM/PM?

### CODE REVIEW

**Comment by corroded** [comment]
In one of our projects, I used a time picker that only used 30 minute intervals. 

check here: http://www.evo-lux.com/

I think this is better unless we need to have on the minute times(11:43, 4:21, etc)

**Comment by crigor** [comment]
Thanks. I think that's better than having a separate dropdown for AM/PM.

**Comment by crigor** [comment]
Ok na ba tong bagong commit?

**Comment by corroded** [comment]
woops sorry di ko nasabi, may plugin na for that. http://tobiascohen.com/demos/calendrical/ 

anyways, okay na din I guess since gumagana naman. gamitin na lang natin yung plugin kung kelangan ireproduce ang time picker anywhere else

**Comment by crigor** [comment]
interesting. http://jqueryui.com/demos/datepicker ang ginamit ko for datepicker pero ung time picker, rails helper ang ginamit ko.

madali lang ba iset ung selected time sa calendrical? mukhang lalagay mo lang sa text field ung value. so f.text_field pwede na? (para sa edit form or pag may missing fields like title, pag show ng page ulit, nakaset na ung time)

**Comment by corroded** [comment]
yup sa f.text_field mo lang seset ang selected time. chneck ko yung code ko
sa evolux default ko lang nga ginamit si calendriaal hehe. basta nag
$("input#date").calendricalTime() lang ako.

On Mon, Jan 23, 2012 at 12:41 AM, Christopher Rigor <
reply@reply.github.com

> wrote:
> 
> interesting. http://jqueryui.com/demos/datepicker ang ginamit ko for
> datepicker pero ung time picker, rails helper ang ginamit ko.
> 
> madali lang ba iset ung selected time sa calendrical? mukhang lalagay mo
> lang sa text field ung value. so f.text_field pwede na? (para sa edit form
> or pag may missing fields like title, pag show ng page ulit, nakaset na ung
> time)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crigor/bayaninhand/pull/20#issuecomment-3604016

## 

Eumir Gaspar
Ruby on Rails Developer/Rails UI Specialist
github: http://github.com/corroded
tech blog: http://aelogica.com/author/eumir/http://blog.admoolabs.com/author/eumir
stackoverflow: http://stackoverflow.com/users/334545/corroded
stackoverflow resume: http://careers.stackoverflow.com/corroded
working with rails:
http://www.workingwithrails.com/person/19554-eumir-gaspar
http://www.workingwithrails.com/person/19554-eumir-gasparlinked in:
http://ph.linkedin.com/pub/eumir-gaspar/7/969/98a
odesk: http://www.odesk.com/users/~~8951a3b425021bda

**Pull request merged**
