### PR TITLE
Organization dashboard

### PR DESCRIPTION
**Pull request by iyanski**
Added organization page
Linked Organizations menu to /organizations

### CODE REVIEW

**Comment by crigor** [comment]
Thanks.

Can you move the page to organization admin? The page you edited is organization show which is public. Can you also remove the css? We'll wait for Aithne for the design. You can also help her with the design if you want, but that's a separate ticket.

**Comment by crigor** [comment]
Ian, the design for the org dashboard is on https://github.com/crigor/ivolunteer_html. Use that instead

**Comment by iyanski** [comment]
ok, thnx.

**Comment by crigor** [comment]
I'll close this since it's out of date. Check redmine for the ticket.

**Pull request closed without merging**
