### PR TITLE
created seed data for Expertise and fixed the expertise alignments

### PR DESCRIPTION
**Pull request by ngdelcastillo**
this for the fix on feature #44

### CODE REVIEW

**Comment by crigor** [comment]
I replied on http://redmine.crigor.com/issues/44

**Comment by crigor** [comment]
@corroded pacheck naman kung tama ung ginawa ko. ayoko maglagay ng extra id or class para lang gumana ung cucumber

**Comment by ngdelcastillo** [comment]
Sorry ngayon ko lang nabasa. Na add na kita as collaborator Eumir. :D

**Comment by crigor** [comment]
@corroded merge ko na lang ulit pag naayos mo na ung tests.

**Pull request merged**
