### PR TITLE
Fix privacy concern

### PR DESCRIPTION
**Pull request by ngdelcastillo**
This is weird. There should only be one commit for this new branch which is the latest one. But there are 17 commits. How can I remove the 16 commits? My fix is just a one liner change which is only a minute. I spent hours of trying to figure out on removing the 16 commits. Need help on this. LOL.

### CODE REVIEW

**Comment by corroded** [comment]
What were the specific things you did? It looks like the previous commits were added again. Did you do a rebase or a merge?

**Comment by ngdelcastillo** [comment]
Actually I'm not sure. What I usually do whenever I start working on a task is to:
git pull upstream master

But I did remember that I tried to play around with merge in my local repo. But then again, I did create a new branch when I finished working on the change which is in commit 8a5123d. That is the only commit you need to pull. It's only a one liner code change, so I guess there won't be any pull request if the change will be directly committed in the upstream. 

I never used rebase. But I'm planning to since I want to remove the other commits in this pull request. I think I made a mistake of pushing the changes in my remote repo without checking the git log. I only did git status.

**Comment by corroded** [comment]
if you only have 1 commit, the surest(not exactly the best) thing i can think of right now is:

```
git format-patch -1 (this creates a patch of your last commit with filename 0001-commit-message.patch)
git checkout master
git pull origin master(get the very latest master branch)
git checkout -b new_fix_privacy_concern
git apply 0001-commit-message.patch
git add <your changes>
git commit -m "your commit message again"
git push origin new_fix_privacy_concern
```

basically, create a patch of your last commit, create a new branch from the latest master branch, add your changes and commit again, and push it again to a new branch.

**Comment by crigor** [comment]
What @corroded said, do it on a new branch. And remove the whole thing. We don't really need  "People who volunteered" on this page yet. I added it at the start of development to help in debugging.

When you run git checkout -b new_branch_name, make sure you're on the master branch. I think a lot of commits showed up because you didn't branch from the master.

**Comment by ngdelcastillo** [comment]
Guys,

I followed your instructions and created a new branch but same issue parin. Nag create naman ako ng new branch sa master. It seems the problem goes to when creating a new branch. Pag nag create ba ng new branch, dapat blank yung git log? sa akin kasi me laman palagi.

**Comment by crigor** [comment]
do this. 

git status # make sure there are no changes
git checkout master
git branch # make sure you're really on master
git checkout -b foo # create new branch
git branch # make sure you're on the foo branch
git status # make sure there are no changes
then edit your code

if you see anything that doesn't look correct, paste it here or on redmine

**Pull request closed without merging**
