### PR TITLE
Add validation for event times. Disable count me in link if volunteers still needed is 0.

### PR DESCRIPTION
**Pull request by gerald**
Add validation for event times. 
Disable count me in link if volunteers still needed is 0.

### CODE REVIEW

**Comment by crigor** [comment]
Hindi required ang start time at end time. Tanggalin mo lang sa validates_presence ayos na.

**Comment by corroded** [comment]
dapat ata imerge mo muna to master tas push uli para pwede ma auto merge from github?

**Comment by gerald** [comment]
Teka ang ginawa ko pinush ko lang uli yung branch so inisip ko nasama na sa
pull request na luma tapos ipull na lang? O mali ba yun?

On Wed, Mar 14, 2012 at 4:37 PM, Eumir Gaspar <
reply@reply.github.com

**Comment by corroded** [comment]
tama naman kaso baka hindi na siya updated with master so hindi mamemerge to master. dun sa branch mo mag `git merge master` ka dapat tas resolve conflicts tas push uli

**Comment by gerald** [comment]
Sinunod ko ang payo ni Eums. Thanks Eums!

**Pull request merged**
